version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'carparkingms'
      MYSQL_USER: 'carpark'
      MYSQL_PASSWORD: 'noobmaster69'
      MYSQL_ROOT_PASSWORD: 'noobmaster69'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/carparking
    ports:
      - "8000:8000"
    depends_on:
      - db
